name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Schritt 1: Checkout des Repository-Codes
      - name: Checkout repository
        uses: actions/checkout@v3

      # Schritt 2: Setup QEMU für Multi-Architektur Builds
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      # Schritt 3: Setup Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Schritt 4: Login bei GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Schritt 5: Definieren des Repository-Namens
      - name: Set repository name
        id: repo-name
        run: echo "REPO_NAME=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV

      # Schritt 6: Bauen und Pushen des Docker Images
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ env.REPO_NAME }}:latest
            ghcr.io/${{ github.repository_owner }}/${{ env.REPO_NAME }}:${{ github.sha }}
          platforms: linux/amd64,linux/arm64

      # Schritt 7 (Optional): Image Metadata setzen
      - name: Image metadata
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository_owner }}/${{ env.REPO_NAME }}
          tags: |
            type=ref,event=branch
            type=sha


            